
colors1 = [:yellow, :pink, :orange, :blue, :green, :purple, :lightblue, :darkgreen, :magenta]
colors2=[:purple,:mediumpurple,:green,:plum,:purple,:lightblue]
colorsr = [:gold, :darkorange, :red]

colors_r=["#ff0000ff","#ff0000ff","#ff0000ff"]
colors_r1=["#e48080ff","#e48080ff","#e48080ff"]
colors_r2=["#bb9fc9ff","#bb9fc9ff","#bb9fc9ff"]
colors_r3=["#4ca7a2ff","#4ca7a2ff","#4ca7a2ff"]
colors_r4=[:pink,:pink,:pink]
colors_r5=[:blue, :blue, :blue]
colors_r6=[:plum, :plum, :plum]
colors_r7=[:purple, :purple, :purple]
colors_r8=[:lightblue,:lightblue,:lightblue]
colors_r9=[:mediumpurple,:mediumpurple,:mediumpurple]
colors_r10=[:magenta,:magenta,:magenta]
colors_r11=[:darkgreen,:darkgreen,:darkgreen]


colors_s=["#ff0000ff","#ff0000ff","#ff0000ff","#ff0000ff","#ff0000ff","#ff0000ff"]
colors_s1=["#e48080ff","#e48080ff","#e48080ff","#e48080ff","#e48080ff","#e48080ff"]
colors_s2=["#bb9fc9ff","#bb9fc9ff","#bb9fc9ff","#bb9fc9ff","#bb9fc9ff","#bb9fc9ff"]
colors_s3=["#4ca7a2ff","#4ca7a2ff","#4ca7a2ff","#4ca7a2ff","#4ca7a2ff","#4ca7a2ff"]
colors_s4=[:pink,:pink,:pink,:pink,:pink,:pink]
colors_s5=[:blue, :blue, :blue,:blue, :blue, :blue]
colors_s6=[:plum, :plum, :plum,:plum, :plum, :plum]
colors_s7=[:purple, :purple, :purple,:purple, :purple, :purple]
colors_s8=[:lightblue,:lightblue,:lightblue,:lightblue,:lightblue,:lightblue]
colors_s9=[:mediumpurple,:mediumpurple,:mediumpurple,:mediumpurple,:mediumpurple,:mediumpurple]
colors_s10=[:magenta,:magenta,:magenta,:magenta,:magenta,:magenta]
colors_s11=[:darkgreen,:darkgreen,:darkgreen,:darkgreen,:darkgreen,:darkgreen]
